src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use phpDocumentor\Reflection\Types\Mixed_;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{

    use TimestampableEntity;

    const PRODUCT_COLORS = [
        'white' => '#ffffff',
        'aqua' => '#72CEDD',
        'orange' => '#FA8171',
        'pink' => '#EE84B5',
        'purple' => '#8914AE'
    ];

    const PRODUCT_TYPES = ['bouquet', 'box', 'vase'];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @JMS\Groups({"client", "delivery"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client", "delivery"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client", "delivery"})
     */
    private $nameAr;


    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client"})
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=ProductColor::class, inversedBy="products")
     * @JMS\Groups({"client"})
     */
    private $color;

    /**
     * @var float
     */
    private $price;


    /**
     * @ORM\Column(type="text", length=255)
     * @JMS\Groups({"client"})
     */
    private $description;

    /**
     * @ORM\Column(type="text", length=255)
     * @JMS\Groups({"client"})
     */
    private $descriptionAr;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @JMS\Groups({"client"})
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductImage", mappedBy="product", cascade={"all"})
     * @JMS\Groups({"client", "delivery"})
     */
    private $images;


    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled = true;

    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client"})
     */
    private $SKU;

    /**
     * @ORM\Column(type="float")
     */
    private $cost;

    /**
     * @ORM\Column(type="float")
     */
    private $benefit;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"client"})
     */
    private $longDescription;

    /**
     * Visible on store field
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visible = true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $discountable = true;

    /**
     * @ORM\Column(type="integer")
     */
    private $views = 0;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="availableProducts")
     * @JMS\Groups({"client"})
     */
    private $users;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @JMS\Groups({"client"})
     */
    private $longDescriptionAr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @JMS\Groups({"client"})
     */
    private $designedBy;

    /**
     * @var int|null
     * @JMS\Groups({"client"})
     * @JMS\SerializedName("count")
     */
    private $countFromServer;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @JMS\Groups({"client", "delivery"})
     */
    private $package = false;




    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getColor(): ?ProductColor
    {
        return $this->color;
    }

    public function setColor(?ProductColor $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->cost + $this->benefit;
    }

    /**
     * @return float
     * @JMS\VirtualProperty()
     * @JMS\SerializedName("price")
     * @JMS\Groups({"client"})
     */
    public function getTotalPrice()
    {
        return $this->getPrice();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|ProductImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ProductImage $image): self
    {
        if (!$this->images->contains($image) && !is_null($image->getImageFile())) {
            $this->images[] = $image;
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(ProductImage $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }


    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }


    public function getSKU(): ?string
    {
        return $this->SKU;
    }

    public function setSKU(string $SKU): self
    {
        $this->SKU = $SKU;

        return $this;
    }

    public function getCost(): ?float
    {
        return $this->cost;
    }

    public function setCost(float $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getBenefit(): ?float
    {
        return $this->benefit;
    }

    public function setBenefit(float $benefit): self
    {
        $this->benefit = $benefit;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    public function setLongDescription(?string $longDescription): self
    {
        $this->longDescription = $longDescription;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(?bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getDiscountable(): ?bool
    {
        return $this->discountable;
    }

    public function setDiscountable(?bool $discountable): self
    {
        $this->discountable = $discountable;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function __toString()
    {
        return $this->SKU . ' - ' . $this->name;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addAvailableProduct($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeAvailableProduct($this);
        }

        return $this;
    }

    public function getLongDescriptionAr(): ?string
    {
        return $this->longDescriptionAr;
    }

    public function setLongDescriptionAr(?string $longDescriptionAr): self
    {
        $this->longDescriptionAr = $longDescriptionAr;

        return $this;
    }

    public function getDesignedBy(): ?string
    {
        return $this->designedBy;
    }

    public function setDesignedBy(?string $designedBy): self
    {
        $this->designedBy = $designedBy;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getCountFromServer(): ?int
    {
        return $this->countFromServer;
    }

    /**
     * @param int|string $countFromServer
     */
    public function setCountFromServer(?int $countFromServer): void
    {
        $this->countFromServer = $countFromServer;
    }

    public function getPackage(): ?bool
    {
        return $this->package;
    }

    public function setPackage(?bool $package): self
    {
        $this->package = $package;

        return $this;
    }

    public function getNameAr(): ?string
    {
        return $this->nameAr;
    }

    public function setNameAr(string $nameAr): self
    {
        $this->nameAr = $nameAr;

        return $this;
    }

    public function getDescriptionAr(): ?string
    {
        return $this->descriptionAr;
    }

    public function setDescriptionAr(string $descriptionAr): self
    {
        $this->descriptionAr = $descriptionAr;

        return $this;
    }

}

templates/order/_form.html.twig
{% import _self as formMacros %}
{% macro printOrderDetailsRow(OrderDetailsForm) %}
    <td>{{ form_widget(OrderDetailsForm.product) }}</td>
    <td>{{ form_widget(OrderDetailsForm.quantity) }}</td>
    <td>
        <button type="button" class="btn delete-order-detail-row" style="padding: 0;">
            <i class="mdi mdi-delete text-danger" style="font-size: 1.5rem"></i>
        </button>
    </td>
{% endmacro %}

{{ form_start(form) }}

<div class="d-flex flex-column ">
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="card-title mt-3 text-info">
                    Order informations
                    <hr>
                </div>
                <div class="d-flex flex-wrap">
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.deliveryDate) }}
                    </div>
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.deliverySlot) }}
                    </div>
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.status) }}
                    </div>
                </div>
                <div class="d-flex flex-wrap">
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.client) }}
                    </div>
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.deliveryAddress) }}
                    </div>
                    <div class="col-md-4 col-sm-12">
                        {{ form_row(form.shop) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="card-title mt-3 text-info">
                    Billing informations
                    <hr>
                </div>
                <div class="d-flex flex-wrap">
                    <div class=" col-md-6 col-sm-12">
                        {{ form_row(form.paymentDate) }}
                    </div>
                    <div class=" col-md-6 col-sm-12">
                        {{ form_row(form.paymentStatus) }}
                    </div>
                    <div class=" col-md-6 col-sm-12">
                        {{ form_row(form.paymentMethod) }}
                    </div>
                    <div class=" col-md-6 col-sm-12">
                        {{ form_row(form.VAT) }}
                    </div>
                    <div class=" col-md-6 col-sm-12">
                        {{ form_row(form.discountVoucher) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="card-title mt-3 text-info">
                    Greetings informations
                    <hr>
                </div>
                <div class="d-flex flex-wrap">
                    <div class="col-md-6 col-sm-12">
                        {{ form_row(form.messageFrom) }}
                    </div>
                    <div class="col-md-6 col-sm-12">
                        {{ form_row(form.messageTo) }}
                    </div>
                    <div class="col-12">
                        {{ form_row(form.messageLink) }}
                    </div>
                    <div class="col-12">
                        {{ form_row(form.message) }}
                    </div>
                    <div class="col-md-6 col-sm-12">
                        {{ form_row(form.messageFile) }}
                    </div>
                    <div class="d-flex align-items-center col-md-6 col-sm-12">
                        {{ form_row(form.hideSender) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="card-title mt-3 text-info">
                    Cart informations
                    <hr>
                </div>
                <div class="table-responsive">
                    <table class="table order-details-table"
                           data-prototype="{{ formMacros.printOrderDetailsRow(form.orderDetails.vars.prototype)|e('html_attr') }}">
                        <thead>
                        <tr>
                            <th style="width: 70%;">Product</th>
                            <th>Quantity</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detail in form.orderDetails %}
                            <tr>
                                <td>{{ form_widget(detail.product) }}</td>
                                <td>{{ form_widget(detail.quantity) }}</td>
                                <td>
                                    <button type="button" class="btn delete-order-detail-row" style="padding: 0;">
                                        <i class="mdi mdi-delete text-danger" style="font-size: 1.5rem"></i>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="card-title mt-3 text-info">
                    Add a note
                    <hr>
                </div>
                <div>
                    {% for note in form.notes|reverse %}
                        {% if note.vars.value.id %}
                            <div style="display: none"> {{ form_widget(note.note) }}</div>
                            <div class="col-12">
                                <h6>{{ note.vars.value.createdAt|date('d M Y H:i') }} By :{{ note.vars.value.user.fullname }} </h6>
                                <p class="ml-3 text-justify">{{ note.vars.value.note }}</p>
                            </div>
                            <hr>
                        {% else %}
                            <div class="col-12">
                                {{ form_widget(note.note) }}
                            </div>
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="w-100 d-flex justify-content-center ">
        <div class="card col-lg-11 mt-3">
            <div class="card-body">
                <div class="d-flex justify-content-around flex-wrap">
                    <button class="btn btn-primary ">{{ button_label|default('Save') }}</button>
                    {% if form.vars.value.id is not null %}
                        <a href="{{ path('order_delete', {id:form.vars.value.id}) }}"
                           class="btn btn-danger ">Delete</a>
                        <a href="{{ path('order_show', {id:form.vars.value.id}) }}"
                           class="btn btn-info ">View</a>
                    {% else %}
                        <input type="hidden" id="willView" name="willView" value="0">
                        <button id="save_view_btn" class="btn btn-info ">Save & View</button>
                    {% endif %}
                    <a href="{{ path('order_index') }}" class="btn btn-light ">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</div>


{{ form_end(form) }}

{% block javascripts %}
    {{ encore_entry_script_tags('order_form') }}
{% endblock %}

{% block stylesheets %}
    <style>
        .select2-container {
            width: 100% !important;
        }
    </style>
{% endblock %}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <div class="page-header">
        <h3 class="page-title">
            Edit order : {{ order.reference }}
        </h3>
    </div>


    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}


{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders list{% endblock %}

{% block body %}

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    <div class="page-header">
        <h3 class="page-title">
            {% if subTitle is defined %} {{ subTitle }}{% endif %} Orders
        </h3>
        {% if is_granted('ROLE_SUPER_ADMIN') or is_granted('ROLE_ADMIN') %}
            <a href="{{ path('order_new') }}">
                <i class="fas fa-plus-circle text-primary icon-md"></i>
            </a>
        {% endif %}
    </div>


    <div class="card" style="min-height: 100%">
        <div class="card-body">
            <div class="table-responsive">
                <table class="data-table table table-hover">
                    <thead>
                    <tr>
                        <th>REF</th>
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                            <th>Amount</th>
                        {% endif %}
                        <th>Date</th>
                        <th>Customer</th>
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                            <th>City</th>
                        {% endif %}
                        <th>Delivery Date</th>
                        <th>Status</th>
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                            <th>Paid</th>
                            <th>Origin</th>
                        {% endif %}
                        <th>Last Note</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.reference }}</td>
                            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                                <td>{{ order.totalPrice }} SAR</td>
                            {% endif %}
                            <td>{{ order.createdAt|date('d/m/Y H:i') }}</td>
                            <td>{{ order.client.fullName }}</td>
                            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') and order.deliveryAddress.recieverArea %}
                                <td>
                                    <a href="{{ path('area_show', {id : order.deliveryAddress.recieverArea.id}) }}"
                                       target="_blank">
                                        {{ order.deliveryAddress.recieverArea }}
                                    </a>
                                </td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td>
                                {% if order.deliverySlot %}
                                    {{ order.deliveryDate|date('d/m/Y') }} {{ order.deliverySlot.deliveryAt|date('ga') }}
                                    - {{ order.deliverySlot.deliveryTo|date('ga') }}
                                {% endif %}
                            </td>
                            <td>
                                {% if(order.status == 'new') %}
                                    {% if order.shop is null %}
                                        <div class="badge badge-warning">
                                            New
                                        </div>
                                    {% else %}
                                        <div class="badge badge-primary">
                                            Assigned to <br> {{ order.shop.fullName }}
                                        </div>
                                    {% endif %}
                                {% elseif(order.status == 'shipped') %}
                                    <div class="badge badge-info">
                                        Delivering
                                    </div>
                                {% elseif(order.status == 'delivered') %}
                                    <div class="badge badge-success">
                                        Delivered by <br> {{ order.driver.fullName ?? '' }}
                                    </div>
                                {% elseif(order.status == 'canceled') %}
                                    <div class="badge badge-danger">
                                        Canceled
                                    </div>
                                {% endif %}
                            </td>
                            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                                <td>
                                    {% if(order.paymentStatus == 'paid') %}
                                        <i class="fas fa-check text-success"
                                           style="font-size: 1.5rem"></i>
                                    {% else %}
                                        <i class="fas fa-times text-danger" style="font-size: 1.5rem"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if(order.orderOrigin == 'ios') %}
                                        <i class="fab fa-apple fa-2x text-info"></i>
                                    {% elseif(order.orderOrigin == 'android') %}
                                        <i class="fab fa-android fa-2x text-info"></i>
                                    {% elseif(order.orderOrigin == 'dashboard') %}
                                        <i class="fas fa-tachometer-alt fa-2x text-info"></i>
                                    {% elseif(order.orderOrigin == 'website') %}
                                        <i class="fab fa-internet-explorer fa-2x text-info"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <div style="height: 60px;overflow: auto;">
                                        {{ order.notes|reverse[0].note ?? '' }}
                                    </div>
                                </td>
                            {% endif %}
                            <td>
                                <a href="{{ path('order_show', {'id': order.id}) }}">
                                    <i class="mdi mdi-eye text-primary" style="font-size: 1.3rem"></i>
                                </a>
                                {% if is_granted('ROLE_SUPER_ADMIN') %}
                                    <a href="{{ path('order_delete', {'id': order.id}) }}">
                                        <i class="mdi mdi-delete text-danger" style="font-size: 1.3rem"></i>
                                    </a>
                                {% endif %}
                                {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                                    <a href="{{ path('order_edit', {'id': order.id}) }}">
                                        <i class="mdi mdi-grease-pencil text-success" style="font-size: 1.3rem"></i>
                                    </a>
                                    <a href="{{ path('cancel_order', {id: order.id}) }}">
                                        <i class="fas fa-times text-info"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add new Order{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    <div class="page-header">
        <h3 class="page-title">
            Add new Order
        </h3>
    </div>

    {{ include('order/_form.html.twig') }}

{% endblock %}