src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use JMS\Serializer\Annotation as JMS;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("phone")
 */
class User implements UserInterface
{

    use TimestampableEntity;

    const USER_ROLES = [
        'shop' => 'ROLE_SHOP',
        'admin' => 'ROLE_ADMIN',
        'superAdmin' => 'ROLE_SUPER_ADMIN',
        'client' => 'ROLE_CLIENT',
        'driver' => 'ROLE_DRIVER',
        'unverified' => 'ROLE_UNVERIFIED'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @JMS\Groups({"client","driver", "basicClient", "default"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true, nullable=true)
     * @JMS\Groups({"client", "basicClient"})
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     * @JMS\Groups({"client","driver", "basicClient", "default"})
     */
    private $role = self::USER_ROLES['client'];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client","driver", "delivery", "basicClient"})
     */
    private $fullName;


    /**
     * @ORM\Column(type="string", length=255)
     * @JMS\Groups({"client","driver", "delivery", "basicClient"})
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active = true;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $accessId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $carId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Area", inversedBy="users")
     * @JMS\Groups({"driver", "delivery", "client"})
     */
    private $area;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", inversedBy="users")
     */
    private $availableProducts;

    /**
     * @ORM\OneToMany(targetEntity=OrderNote::class, mappedBy="user")
     */
    private $orderNotes;

    /**
     * @ORM\OneToMany(targetEntity=DeliveryAddress::class, mappedBy="client", cascade={"all"})
     */
    private $deliveryAddresses;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="client")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="driver", cascade={"persist"})
     */
    private $driverOrders;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastVisit;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @JMS\Groups({"client", "basicClient"})
     */
    private $balance = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $verificationCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $plainRole;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="sender")
     */
    private $sentMessages;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="reciever")
     */
    private $recievedMessages;


    public function __construct()
    {
        $this->availableProducts = new ArrayCollection();
        $this->orderNotes = new ArrayCollection();
        $this->deliveryAddresses = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->driverOrders = new ArrayCollection();
        $this->sentMessages = new ArrayCollection();
        $this->recievedMessages = new ArrayCollection();
    }


    public function getVerificationCode(): ?string
    {
        return $this->verificationCode;
    }

    public function setVerificationCode(?string $verificationCode): self
    {
        $this->verificationCode = $verificationCode;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }


    public function getRole(): string
    {
        $role = $this->role ?? self::USER_ROLES['client'];

        return $role;
    }

    public function getRoles()
    {
        return [$this->getRole()];
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(?string $password): self
    {
        if (!is_null($password)) {
            $this->password = $password;
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getAccessId(): ?string
    {
        return $this->accessId;
    }

    public function setAccessId(?string $accessId): self
    {
        $this->accessId = $accessId;

        return $this;
    }

    public function getCarId(): ?string
    {
        return $this->carId;
    }

    public function setCarId(?string $carId): self
    {
        $this->carId = $carId;

        return $this;
    }

    public function getArea(): ?Area
    {
        return $this->area;
    }

    public function setArea(?Area $area): self
    {
        $this->area = $area;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getAvailableProducts(): Collection
    {
        return $this->availableProducts;
    }

    public function addAvailableProduct(Product $availableProduct): self
    {
        if (!$this->availableProducts->contains($availableProduct)) {
            $this->availableProducts[] = $availableProduct;
        }

        return $this;
    }

    public function removeAvailableProduct(Product $availableProduct): self
    {
        if ($this->availableProducts->contains($availableProduct)) {
            $this->availableProducts->removeElement($availableProduct);
        }

        return $this;
    }

    /**
     * @return Collection|OrderNote[]
     */
    public function getOrderNotes(): Collection
    {
        return $this->orderNotes;
    }

    public function addOrderNote(OrderNote $orderNote): self
    {
        if (!$this->orderNotes->contains($orderNote)) {
            $this->orderNotes[] = $orderNote;
            $orderNote->setUser($this);
        }

        return $this;
    }

    public function removeOrderNote(OrderNote $orderNote): self
    {
        if ($this->orderNotes->contains($orderNote)) {
            $this->orderNotes->removeElement($orderNote);
            // set the owning side to null (unless already changed)
            if ($orderNote->getUser() === $this) {
                $orderNote->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DeliveryAddress[]
     */
    public function getDeliveryAddresses(): Collection
    {
        return $this->deliveryAddresses;
    }

    public function addDeliveryAdress(DeliveryAddress $deliveryAdress): self
    {
        if (!$this->deliveryAddresses->contains($deliveryAdress)) {
            $this->deliveryAddresses[] = $deliveryAdress;
            $deliveryAdress->setClient($this);
        }

        return $this;
    }

    public function removeDeliveryAdress(DeliveryAddress $deliveryAdress): self
    {
        if ($this->deliveryAddresses->contains($deliveryAdress)) {
            $this->deliveryAddresses->removeElement($deliveryAdress);
            // set the owning side to null (unless already changed)
            if ($deliveryAdress->getClient() === $this) {
                $deliveryAdress->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setClient($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getClient() === $this) {

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\ProductImage;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fullName', TextType::class, [
                'label' => 'Full name'
            ])
            ->add('phone', TextType::class, [
                'label' => 'Phone number'
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email adress',
                'required' => true,
                'constraints' => [
                    new NotBlank(),
                    new Email()
                ]
            ])
            ->add('active', CheckboxType::class, [
                'label_attr' => ['class' => 'switch-custom'],
                'required' => false
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'The password fields must match.',
                'options' => ['attr' => ['class' => 'password-field']],
                'required' => false,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat Password'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_form.html.twig
<div class="d-flex justify-content-center">
    <div class="card col-lg-6">
        <div class="card-body">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <div class="d-flex justify-content-around flex-wrap">
                <button class="btn btn-primary ">{{ button_label|default('Save') }}</button>
                {% if form.vars.value.id is not null %}
                    <a href="{{ path('user_delete', {id:form.vars.value.id}) }}" class="btn btn-danger ">Delete</a>
                {% endif %}
                <a href="{{ path('user_index', {'role':'all'}) }}" class="btn btn-light ">Cancel</a>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/user/client_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client details{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    <div class="page-header">
        <h3 class="page-title">
            Client details : {{ client.fullName }}
        </h3>
        <h4 class="mr-5">Personal Balance : {{ client.balance ?? 0 }} SAR</h4>
    </div>

    <div class="d-flex flex-column ">
        <div class="w-100 d-flex justify-content-center ">
            <div class="card col-lg-11 mt-3">
                <div class="card-body">
                    <div class="card-title mt-3 text-info">
                        General informations
                        <hr>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ client.fullName }}</td>
                                <td>{{ client.phone }}</td>
                                <td>{{ client.email }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-100 d-flex justify-content-center ">
            <div class="card col-lg-11 mt-3">
                <div class="card-body">
                    <div class="card-title mt-3 text-info">
                        Delivery addresses
                        <hr>
                    </div>
                    <div class="table-responsive">
                        <table class="data-table table">
                            <thead>
                            <tr>
                                <th>Reciever name</th>
                                <th>Reciever phone</th>
                                <th>Reciever full address</th>
                                <th>Reciever City</th>
                                <th>Reciever locations</th>
                                <th>Additional notes</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for address in client.deliveryAddresses %}
                                <tr>
                                    <td>{{ address.recieverName }}</td>
                                    <td>{{ address.recieverPhone }}</td>
                                    <td>{{ address.recieverFullAddress }}</td>
                                    <td>
                                        {% if address.recieverArea.id is defined %}
                                            <a target="_blank"
                                               href="{{ path('area_show', {id : address.recieverArea.id}) }}">
                                                {{ address.recieverArea.nameEn }}
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td>{{ address.recieverLocations }}</td>
                                    <td>{{ address.notes }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-100 d-flex justify-content-center ">
            <div class="card col-lg-11 mt-3">
                <div class="card-body">
                    <div class="card-title mt-3 text-info">
                        Previous orders
                        <hr>
                    </div>
                    <div class="table-responsive">
                        <table class="data-table table">
                            <thead>
                            <tr>
                                <th>Reference</th>
                                <th>Amount</th>
                                <th>Date</th>
                                <th>Delivery Date</th>
                                <th>Status</th>
                                <th>Payment</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in client.orders|reverse %}
                                <tr>
                                    <td>
                                        <a target="_blank" href="{{ path('order_show', {id: order.id}) }}">
                                            {{ order.reference }}
                                        </a>
                                    </td>
                                    <td>{{ order.totalPrice }} SAR</td>
                                    <td>{{ order.createdAt|date('d/m/Y H:i') }}</td>
                                    <td>{{ order.deliveryDate|date('d/m/Y') }} {{ order.deliverySlot.deliveryAt|date('ga') }}
                                        - {{ order.deliverySlot.deliveryTo|date('ga') }}</td>
                                    <td>
                                        {% if(order.status == 'new') %}
                                            <div class="badge badge-warning">
                                                New
                                            </div>
                                        {% elseif(order.status == 'shipped') %}
                                            <div class="badge badge-info">
                                                Shipped
                                            </div>
                                        {% elseif(order.status == 'delivered') %}
                                            <div class="badge badge-success">
                                                Delivered
                                            </div>
                                        {% elseif(order.status == 'canceled') %}
                                            <div class="badge badge-danger">
                                                Canceled
                                            </div>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if(order.paymentStatus == 'paid') %}
                                            <div class="badge badge-success">
                                                Paid
                                            </div>
                                        {% elseif(order.paymentStatus == 'not_paid') %}
                                            <div class="badge badge-danger">
                                                Not Paid
                                            </div>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-100 d-flex justify-content-center ">
            <div class="card col-lg-11 mt-3">
                <div class="card-body">
                    <div class="d-flex justify-content-around flex-wrap">
                        <button class="btn btn-success"
                                type="button"
                                data-toggle="modal"
                                data-target="#modalAddBalance">
                            Add balance
                        </button>
                        <button class="btn btn-danger"
                                type="button"
                                data-toggle="modal"
                                data-target="#modalDeductBalance">
                            Deduct balance
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="modal fade" id="modalAddBalance" tabindex="-1" role="dialog"
         aria-labelledby="modalNoteTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{ path('balance_control', {type: 'add', id: client.id}) }}" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalNoteTitle">Add balance</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="amount">Amount</label>
                            <input type="text" name="amount" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="submit-inventory" type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" id="modalDeductBalance" tabindex="-1" role="dialog"
         aria-labelledby="modalNoteTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{{ path('balance_control', {type: 'deduct', id: client.id}) }}" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalNoteTitle">Deduct balance</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="amount">Amount</label>
                            <input type="text" name="amount" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="submit-inventory" type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/user/drivers_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List drivers{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    <div class="page-header">
        <h3 class="page-title">
            Drivers
        </h3>
        <a href="{{ path('user_new', {role: 'driver'}) }}">
            <i class="mdi mdi-account-plus text-primary icon-md"></i>
        </a>
    </div>

    <div class="card" style="min-height: 100%">
        <div class="card-body">
            <div class="table-responsive">
                <table class="data-table table table-hover">
                    <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Phone</th>
                        <th>Last visit</th>
                        <th>Orders</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.fullName }}</td>
                            <td>{{ user.phone }}</td>
                            {% if user.lastVisit is not null %}
                                <td>{{ user.lastVisit|date('d/m/Y H:i') }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td>{{ user.driverOrders|length }}</td>
                            <td>
                                <a href="{{ path('user_show', {'id': user.id}) }}">
                                    <i class="mdi mdi-eye text-primary" style="font-size: 1.3rem"></i>
                                </a>
                                <a href="{{ path('user_delete', {'id': user.id}) }}">
                                    <i class="mdi mdi-delete text-danger" style="font-size: 1.3rem"></i>
                                </a>
                                <a href="{{ path('user_edit', {'id': user.id}) }}">
                                    <i class="mdi mdi-grease-pencil text-success" style="font-size: 1.3rem"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascripts %}
    {{ encore_entry_script_tags('user') }}
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit {{ title }}{% endblock %}

{% block body %}

    <div class="page-header">
        <h3 class="page-title">
            Edit {{ title }}
        </h3>
    </div>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List users{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    <div class="page-header">
        <h3 class="page-title">
            {% if app.session.get('activeMenu') == 'users' %}
                All users
            {% else %}
                {{ app.session.get('activeMenu')|capitalize }}s
            {% endif %}
        </h3>
        {% if title in ['admin', 'client', 'shop'] %}
            <a href="{{ path('user_new', {role: title}) }}">
                <i class="mdi mdi-account-plus text-primary icon-md"></i>
            </a>
        {% endif %}
    </div>

    <div class="card" style="min-height: 100%">
        <div class="card-body">
            <div class="table-responsive">
                <table class="data-table table table-hover">
                    <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Role</th>
                        <th>Active</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.fullName }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.phone }}</td>
                            <td>
                                {% if 'ROLE_SUPER_ADMIN' in user.roles %}
                                    Super admin
                                {% elseif 'ROLE_ADMIN' in user.roles %}
                                    Admin
                                {% elseif 'ROLE_SHOP' in user.roles %}
                                    Shop
                                {% elseif 'ROLE_DRIVER' in user.roles %}
                                    Driver
                                {% else %}
                                    Client
                                {% endif %}
                            </td>
                            <td>
                                <div class="custom-control custom-switch">
                                    <input {{ user.active == '1' ? 'checked' : '' }}
                                            type="checkbox" class="custom-control-input"
                                            id="customSwitch{{ loop.index }}">
                                    <label data-id-user="{{ user.id }}"
                                           class="custom-control-label user-toggle-active-switch"
                                           for="customSwitch{{ loop.index }}"></label>
                                </div>
                            </td>
                            <td>
                                {% if user.role in ['ROLE_SHOP', 'ROLE_CLIENT'] %}
                                    <a href="{{ path('user_show', {'id': user.id}) }}">
                                        <i class="mdi mdi-eye text-primary" style="font-size: 1.3rem"></i>
                                    </a>
                                {% endif %}
                                <a href="{{ path('user_delete', {'id': user.id}) }}">
                                    <i class="mdi mdi-delete text-danger" style="font-size: 1.3rem"></i>
                                </a>
                                <a href="{{ path('user_edit', {'id': user.id}) }}">
                                    <i class="mdi mdi-grease-pencil text-success" style="font-size: 1.3rem"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}


{% block javascripts %}
    {{ encore_entry_script_tags('user') }}
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add new {{ title }}{% endblock %}

{% block body %}
    <div class="page-header">
        <h3 class="page-title">
            Add new {{title}}
        </h3>
    </div>

    {{ include('user/_form.html.twig') }}

{% endblock %}